#!/usr/bin/env python3

"""
The UNI-T UT61E+ digital multi-meter data acquisition tool
"""

import hid
import sys
import math
import time
import argparse
from ut61ep import *
from ut61stat import StatCollector

class Plotter:
    """Data plotter"""
    padding = .075

    def __init__(self, args):
        import matplotlib.pyplot as plt
        plt.ion()
        self.plt = plt
        self.args = args
        if args.alt_file:
            nchan = 2 # dual channel plot
            self.fig, self.ax = self.plt.subplots(2, 1, sharex = True)
            if args.alt_title:
                self.ax[1].set_title(args.alt_title)
        else:
            nchan = 1
            self.fig, ax = self.plt.subplots()
            self.ax = [ax]
        if args.plot_title:
            self.ax[0].set_title(args.plot_title)
        self.x_data, self.y_data = [[] for _ in range(nchan)], [[] for _ in range(nchan)]
        self.line = [self.ax[i].plot(self.x_data[i], self.y_data[i])[0] for i in range(nchan)]
        self.vmin, self.vmax = [float('inf')] * nchan, [float('-inf')] * nchan
        if args.title:
            self.fig.canvas.manager.set_window_title(args.title)
        if args.save_on_close:
            self.fig.canvas.mpl_connect('close_event', self.on_close)

    def on_close(self, evt):
        self.fig.savefig(self.args.save_on_close, bbox_inches='tight', dpi=self.args.save_dpi)

    def is_closed(self):
        return not self.plt.fignum_exists(self.fig.number)

    def update_xlim(self, chan, xmin, xmax):
        ax = self.ax[chan]
        if xmin == xmax:
            xmax += args.interval if self.args.interval else 1
        ax.set_xlim(xmin, xmax)

    def update_ylim(self, chan, ymin, ymax):
        ax = self.ax[chan]
        if ymin > 0 and self.args.with_zero:
            vmin = 0
            vmax = ymax * (1 + self.padding)
        elif ymax < 0 and self.args.with_zero:
            vmax = 0
            vmin = ymin * (1 + self.padding)
        else:
            vrange = ymax - ymin if ymax > ymin else abs(ymax) if ymax else 1
            vmin = ymin - vrange * self.padding
            vmax = ymax + vrange * self.padding
        ax.set_ylim(vmin, vmax)

    def update(self, t, val, chan):
        if not math.isnan(val) and chan < len(self.ax):
            self.vmin[chan] = min(self.vmin[chan], val)
            self.vmax[chan] = max(self.vmax[chan], val)
            wnd = self.args.wnd
            xdata, ydata = self.x_data[chan], self.y_data[chan]
            xdata.append(t)
            ydata.append(val)
            pan_zoom = self.ax[chan].get_navigate_mode() is not None
            while wnd and not pan_zoom and len(xdata) > wnd:
                xdata.pop(0)
                ydata.pop(0)
            self.line[chan].set_data(xdata, ydata)
            if not pan_zoom:
                if not chan:
                    self.update_xlim(chan, xdata[0], xdata[-1])
                self.update_ylim(chan, *((min(ydata), max(ydata)) if wnd else (self.vmin[chan], self.vmax[chan])))
        self.fig.canvas.flush_events()
        self.plt.show()


def do_list(args):
    for dev in hid.enumerate(args.VID, args.PID):
        print(dev['path'].decode('ascii'))
    return 0

def open_device(args):
    if args.path:
        return dev_open_path(args.path.encode('ascii'))
    else:
        return dev_open(args.VID, args.PID)

def do_once(args):
    dev = open_device(args)
    if dev is None:
        return -1
    try:
        data = dev_query_raw(dev, args.tout)
        if not data:
            log.error('no data')
            return -1
        print(get_value(data))
        return 0
    finally:
        dev.close()

def do_data(args):
    dev = open_device(args)
    if dev is None:
        return -1
    out_fmt = '%.3f%s %f'
    out_file = sys.stdout if not args.file else open(args.file, 'w')
    alt_file = None if not args.alt_file else open(args.alt_file, 'w')
    stat = [StatCollector(), StatCollector()]
    if args.graph:
        plotter = Plotter(args)
        sleep_fn = plotter.plt.pause
    else:
        plotter = None
        sleep_fn = time.sleep
    try:
        start = ts = time.time()
        while True:
            # Query data
            data = dev_query_raw(dev, args.tout, sleep_fn)
            if not data:
                log.error('no data')
                return -1
            t = ts - start
            val = get_value(data)
            val_chan = get_channel(data)
            val_good = not math.isnan(val)
            # Output data
            if val_chan == 0:
                if val_good: # apply value transformation
                    val = (val - args.offset) * args.mult
                print(out_fmt % (ts if args.epoch else t, args.delimiter, val), file=out_file)
            elif alt_file:
                print(out_fmt % (ts if args.epoch else t, args.delimiter, val), file=alt_file)
            if args.file and args.progress:
                # Show progress
                print('.' if val_good else '!', end='', flush=True)
            if args.stat:
                # Update stat
                stat[val_chan].account(val)
            if plotter:
                if plotter.is_closed():
                    return 0
                # Update plot
                plotter.update(t, val, val_chan)
            # Introduce delay according to acquisition interval
            now = time.time()
            elapsed = now - ts
            if elapsed < args.interval:
                sleep_fn(args.interval - elapsed)
                ts += args.interval
            else:
                ts = now
    except KeyboardInterrupt:
        return 0
    finally:
        dev.close()
        if args.file:
            out_file.close()
            if args.progress:
                print()
        if args.alt_file:
            alt_file.close()
        if args.stat:
            print('\n--- data statistics:')
            stat[0].print()
            if args.alt_file:
                print('\n--- alternative channel:')
                stat[1].print()

def main():
    parser = argparse.ArgumentParser(
            description='UNI-T UT61E+ data acquisition tool',
            usage='%(prog)s [options] list|once|data [command options]'
        )

    def get_help(args):
        parser.print_help()
        return 1

    parser.set_defaults(func=get_help)

    parser.add_argument('--VID', type=int, required=False, default=DEF_VID,
            help='device vendor id (optional)')
    parser.add_argument('--PID', type=int, required=False, default=DEF_PID,
            help='device product id (optional)')
    parser.add_argument('--path', type=str, required=False,
            help='device path (optional, auto detect by default)')
    parser.add_argument('--tout', type=float, required=False, default=DEF_TOUT, metavar='SECONDS',
            help='device read timeout (optional, default is %.0f sec)' % DEF_TOUT)

    subparsers = parser.add_subparsers()
    subparsers.add_parser('list',
            help='list path for connected devices'
        ).set_defaults(func=lambda args: do_list(args))
    subparsers.add_parser('once',
            help='get single reading'
        ).set_defaults(func=lambda args: do_once(args))
    data_parser = subparsers.add_parser('data',
            help='read data continuously',
            formatter_class=lambda prog: argparse.HelpFormatter(prog, max_help_position=40)
        )
    data_parser.set_defaults(func=lambda args: do_data(args))

    data_parser.add_argument('-i', '--interval', type=float, required=False, default=1., metavar='SECONDS',
            help='data acquisition interval (default is 1 sec)')
    data_parser.add_argument('-f', '--file', type=str, required=False, metavar='FILENAME',
            help='output file name (optional, output to stdout by default)')
    data_parser.add_argument('-a', '--alt-file', type=str, required=False, metavar='FILENAME',
            help='alternative channel output file name (for storing AC voltage in DC mode)')
    data_parser.add_argument('-p', '--progress', action='store_true',
            help='show progress when writing to file')
    data_parser.add_argument('-o', '--offset', type=float, required=False, metavar='VALUE', default=0,
            help='set data offset')
    data_parser.add_argument('-m', '--mult', type=float, required=False, metavar='VALUE', default=1,
            help='set data multiplier')
    data_parser.add_argument('-e', '--epoch', action='store_true',
            help='use epoch timestamps (optional, use time since start by default)')
    data_parser.add_argument('-d', '--delimiter', type=str, default='', metavar='SYMBOL',
            help='data delimiter on output (optional, space by default)')
    data_parser.add_argument('-s', '--stat', action='store_true',
            help='output statistic upon termination')
    data_parser.add_argument('-g', '--graph', action='store_true',
            help='show data graph')
    data_parser.add_argument('-w', '--wnd', type=int, required=False, metavar='SAMPLES',
            help='data graph window samples (optional, show all samples by default)')
    data_parser.add_argument('-z', '--with-zero', action='store_true',
            help='make sure zero is within data graph vertical axis range')
    data_parser.add_argument('-t', '--title', type=str, required=False, metavar='TEXT',
            help='set data graph window title')
    data_parser.add_argument('--plot-title', type=str, required=False, metavar='TEXT',
            help='set data plot title')
    data_parser.add_argument('--alt-title', type=str, required=False, metavar='TEXT',
            help='set alternative channel data plot title')
    data_parser.add_argument('--save-on-close', type=str, required=False, metavar='FILENAME',
            help='save figure to specified file on closing')
    data_parser.add_argument('--save-dpi', type=int, required=False, metavar='DPI', default=180,
            help='saving figure resolution (optional, default is 180)')

    args = parser.parse_args()
    return args.func(args)

if __name__ == '__main__':
    sys.exit(main())
