#!/usr/bin/env python3

"""
The UNI-T UT61E+ digital multi-meter data acquisition tool
"""

import hid
import sys
import math
import time
import argparse
from ut61ep import *

def do_list(args):
    for dev in hid.enumerate(args.VID, args.PID):
        print(dev['path'].decode('ascii'))
    return 0

def open_device(args):
    if args.path:
        return dev_open_path(args.path.encode('ascii'))
    else:
        return dev_open(args.VID, args.PID)

def do_once(args):
    dev = open_device(args)
    if dev is None:
        return -1
    try:
        data = dev_query_raw(dev, args.tout)
        if not data:
            log.error('no data')
            return -1
        print(get_value(data))
        return 0
    finally:
        dev.close()

def ax_update_xlim(ax, args, xmin, xmax):
    if xmin == xmax:
        xmax += args.interval if args.interval else 1
    ax.set_xlim(xmin, xmax)

def ax_update_ylim(ax, args, ymin, ymax):
    padding = .075
    if ymin > 0 and args.with_zero:
        vmin = 0
        vmax = ymax * (1 + padding)
    elif ymax < 0 and args.with_zero:
        vmax = 0
        vmin = ymin * (1 + padding)
    else:
        vrange = ymax - ymin if ymax > ymin else abs(ymax) if ymax else 1
        vmin = ymin - vrange * padding
        vmax = ymax + vrange * padding
    ax.set_ylim(vmin, vmax)

def do_data(args):
    dev = open_device(args)
    if dev is None:
        return -1
    out_file = sys.stdout if not args.file else open(args.file, 'w')
    total_samples = total_valid = 0
    total_sum = total_sum2 = total_sum3 = 0
    total_min = float('inf')
    total_max = -total_min
    if args.graph:
        import matplotlib.pyplot as plt
        plt.ion()
        x_data, y_data = [], []
        fig, ax = plt.subplots()
        if args.title:
            fig.canvas.manager.set_window_title(args.title)
        line, = ax.plot(x_data, y_data)
    try:
        start = ts = time.time()
        while True:
            # Query data
            data = dev_query_raw(dev, args.tout)
            if not data:
                log.error('no data')
                return -1
            t = ts - start
            val = get_value(data)
            val_good = not math.isnan(val)
            print('%.3f%s %f' % (ts if args.epoch else t, args.delimiter, val), file=out_file)
            if args.file and args.progress:
                print('.' if val_good else '!', end='', flush=True)
            total_samples += 1
            if val_good:
                val = (val - args.offset) * args.mult
                # Update stat
                total_valid += 1
                total_sum   += val
                total_sum2  += val * val
                total_sum3  += val * val * val
                total_min    = min(total_min, val)
                total_max    = max(total_max, val)
            if args.graph and val_good:
                # Update plot
                if not plt.fignum_exists(fig.number):
                    return 0
                x_data.append(t)
                y_data.append(val)
                pan_zoom = ax.get_navigate_mode() is not None
                while args.wnd and not pan_zoom and len(x_data) > args.wnd:
                    x_data.pop(0)
                    y_data.pop(0)
                line.set_data(x_data, y_data)
                if not pan_zoom:
                    ax_update_xlim(ax, args, x_data[0], x_data[-1])
                    ax_update_ylim(ax, args, *((min(y_data), max(y_data)) if args.wnd else (total_min, total_max)))
            if args.graph:
                fig.canvas.flush_events()
                plt.show()
            # Introduce delay according to acquisition interval
            now = time.time()
            elapsed = now - ts
            if elapsed < args.interval:
                delay = args.interval - elapsed
                if args.graph:
                    plt.pause(delay)
                else:
                    time.sleep(delay)
                ts += args.interval
            else:
                ts = now
    except KeyboardInterrupt:
        return 0
    finally:
        dev.close()
        if args.file:
            out_file.close()
            if args.progress:
                print()
        if args.stat:
            # Output statistics
            print('total samples : %d' % total_samples)                
            print('valid samples : %d' % total_valid)
            if total_valid:
                aver, aver2 = total_sum / total_valid, total_sum2 / total_valid
                aver_2  = aver * aver
                sigma_2 = aver2 - aver_2
                sigma   = math.sqrt(sigma_2) if sigma_2 > 0 else 0
                m3      = total_sum3 / total_valid - aver * (aver_2 + 3 * sigma_2)
                print('min  value    : %f' % total_min)
                print('max  value    : %f' % total_max)
                print('aver value    : %f' % aver)
                print('std deviation : %f' % sigma)
                if aver:
                    print('rel. dev. [%%] : %.2f' % (100 * sigma / abs(aver)))
                if sigma:
                    print('skewness  [%%] : %.2f' % (100 * m3 / (sigma ** 3)))

def main():
    parser = argparse.ArgumentParser(
            description='UNI-T UT61E+ data acquisition tool',
            usage='%(prog)s [options] list|once|data',
            formatter_class=lambda prog: argparse.HelpFormatter(prog, max_help_position=30)
        )

    def get_help(args):
        parser.print_help()
        return 1

    parser.set_defaults(func=get_help)

    parser.add_argument('--VID', type=int, required=False, default=DEF_VID,
            help='device vendor id (optional)')
    parser.add_argument('--PID', type=int, required=False, default=DEF_PID,
            help='device product id (optional)')
    parser.add_argument('--path', type=str, required=False,
            help='device path (optional, auto detect by default)')
    parser.add_argument('--tout', type=float, required=False, default=DEF_TOUT, metavar='SECONDS',
            help='device read timeout (optional, default is %.0f sec)' % DEF_TOUT)
    parser.add_argument('-i', '--interval', type=float, required=False, default=1., metavar='SECONDS',
            help='data acquisition interval (default is 1 sec)')
    parser.add_argument('-f', '--file', type=str, required=False, metavar='FILENAME',
            help='output file name (optional, output to stdout by default)')
    parser.add_argument('-p', '--progress', action='store_true',
            help='show progress when writing to file')
    parser.add_argument('-o', '--offset', type=float, required=False, metavar='VALUE', default=0,
            help='set data offset')
    parser.add_argument('-m', '--mult', type=float, required=False, metavar='VALUE', default=1,
            help='set data multiplier')
    parser.add_argument('-e', '--epoch', action='store_true',
            help='use epoch timestamps (optional, use time since start by default)')
    parser.add_argument('-d', '--delimiter', type=str, default='', metavar='SYMBOL',
            help='data delimiter on output (optional, space by default)')
    parser.add_argument('-s', '--stat', action='store_true',
            help='output statistic upon termination')
    parser.add_argument('-g', '--graph', action='store_true',
            help='show data graph')
    parser.add_argument('-w', '--wnd', type=int, required=False, metavar='SAMPLES',
            help='data graph window samples (optional, show all samples by default)')
    parser.add_argument('-z', '--with-zero', action='store_true',
            help='make sure zero is within data graph vertical axis range')
    parser.add_argument('-t', '--title', type=str, required=False, metavar='NAME',
            help='set data graph window title')

    subparsers = parser.add_subparsers()
    subparsers.add_parser('list',
            help='list path for connected devices'
        ).set_defaults(func=lambda args: do_list(args))
    subparsers.add_parser('once',
            help='get single reading'
        ).set_defaults(func=lambda args: do_once(args))
    subparsers.add_parser('data',
            help='read data continuously'
        ).set_defaults(func=lambda args: do_data(args))

    args = parser.parse_args()
    return args.func(args)

if __name__ == '__main__':
    sys.exit(main())
