#!/usr/bin/env python3

"""
The UNI-T UT61B/D/E+ digital multimeter data acquisition and plotting tool
"""

import os
import sys
import math
import time
import json
import argparse
from ut61xp import log, DEF_TOUT, DEF_VID, DEF_PID, DEF_BT_NAME, Device, HIDDevice, BTDevice
from data_stat import StatCollector
from datetime import datetime

class Plotter:
    """Data plotter"""
    padding = .075

    def __init__(self, args):
        import matplotlib.pyplot as plt
        plt.rcParams["figure.raise_window"] = False
        plt.ion()
        self.plt = plt
        self.args = args
        if args.alt_file:
            nchan = 2 # dual channel plot
            self.fig, self.ax = self.plt.subplots(2, 1, sharex = True)
            if args.alt_title:
                self.ax[1].set_title(args.alt_title)
            if args.alt_hline:
                for y in args.alt_hline:
                    self.ax[1].axhline(y, linestyle=args.hline_style, color=args.hline_color)
        else:
            nchan = 1
            self.fig, ax = self.plt.subplots()
            self.ax = [ax]
        if args.plot_title:
            self.ax[0].set_title(args.plot_title)
        if args.hline:
            for y in args.hline:
                self.ax[0].axhline(y, linestyle=args.hline_style, color=args.hline_color)

        self.x_data, self.y_data = [[] for _ in range(nchan)], [[] for _ in range(nchan)]
        self.line = [self.ax[i].plot(
                self.x_data[i], self.y_data[i],
                linestyle=args.line_style,
                color=(args.line_color, args.alt_line_color)[i]
            )[0] for i in range(nchan)]
        self.vmin, self.vmax = [float('inf')] * nchan, [float('-inf')] * nchan
        if args.title:
            self.fig.canvas.manager.set_window_title(args.title)

    def is_closed(self):
        return not self.plt.fignum_exists(self.fig.number)

    def update_xlim(self, chan, xmin, xmax):
        ax = self.ax[chan]
        if xmin == xmax:
            xmax += self.args.interval if self.args.interval else 1
        ax.set_xlim(xmin, xmax)

    def update_ylim(self, chan, ymin, ymax):
        ax = self.ax[chan]
        hlines = self.args.hline if not chan else self.args.alt_hline
        if hlines:
            for y in hlines:
                ymin = min(ymin, y)
                ymax = max(ymax, y)
        if ymin > 0 and self.args.with_zero:
            vmin = 0
            vmax = ymax * (1 + self.padding)
        elif ymax < 0 and self.args.with_zero:
            vmax = 0
            vmin = ymin * (1 + self.padding)
        else:
            vrange = ymax - ymin if ymax > ymin else abs(ymax) if ymax else 1
            vmin = ymin - vrange * self.padding
            vmax = ymax + vrange * self.padding
        ax.set_ylim(vmin, vmax)

    def update(self, t, val, chan):
        if not math.isnan(val) and chan < len(self.ax):
            self.vmin[chan] = min(self.vmin[chan], val)
            self.vmax[chan] = max(self.vmax[chan], val)
            wnd = self.args.wnd
            xdata, ydata = self.x_data[chan], self.y_data[chan]
            xdata.append(t)
            ydata.append(val)
            pan_zoom = self.ax[chan].get_navigate_mode() is not None
            while wnd and not pan_zoom and len(xdata) > wnd:
                xdata.pop(0)
                ydata.pop(0)
            self.line[chan].set_data(xdata, ydata)
            if not pan_zoom:
                if not chan:
                    self.update_xlim(chan, xdata[0], xdata[-1])
                self.update_ylim(chan, *((min(ydata), max(ydata)) if wnd else (self.vmin[chan], self.vmax[chan])))
        self.fig.canvas.flush_events()
        self.plt.show()

def do_list(args):
    if not args.bt:
        for path in HIDDevice.list_paths(args.VID, args.PID):
            print(path.decode('ascii'))
    else:
        for addr in BTDevice.list_addrs(args.name):
            print(addr)
    return 0

def open_device(args):
    """Open HID or BT device"""
    if args.path:
        return BTDevice.open_addr(args.path) if args.bt else HIDDevice.open_path(args.path)
    return BTDevice.open(args.name) if args.bt else HIDDevice.open(args.VID, args.PID)

def do_once(args):
    """Read and print single value"""
    dev = open_device(args)
    if dev is None:
        return -1
    try:
        data = dev.query_raw(args.tout)
        if not data:
            log.error('\nno data')
            return -1
        print(Device.get_value(data))
        return 0
    finally:
        dev.close()

def maybe_save_cfg(args, dev_path):
    """Save configuration if necessary"""
    cfg_save_fname = getattr(args, 'cfg_save', None)
    if cfg_save_fname:
        opts = args.__dict__.copy()
        del opts['func']
        opts['cfg_save'] = None
        opts['path'] = dev_path
        with open(cfg_save_fname, 'w') as f:
            f.write(json.dumps(opts))

def get_fname(fname_str):
    """Makes filename from parameter string and makes sure folder part exists"""
    if not fname_str:
        return None
    fname = datetime.now().strftime(fname_str) if '%' in fname_str else fname_str
    dirname = os.path.dirname(fname)
    if dirname:
        try:
            os.mkdir(dirname)
        except FileExistsError:
            pass
    return fname

def do_data(args):
    """
    Read data continuously and plot them if -g option is present in args.
    The read loop ends either by typing Ctr-C (without -g option) or by
    closing data graph window.
    """
    dev = open_device(args)
    if dev is None:
        return -1

    maybe_save_cfg(args, dev.path)
    fname, alt_fname = get_fname(args.file), get_fname(args.alt_file)

    out_fmt = '%.3f%s %f'
    out_file = sys.stdout if not fname else open(fname, 'w')
    alt_file = None if not alt_fname else open(alt_fname, 'w')
    stat = [StatCollector(), StatCollector()]
    if args.graph:
        plotter = Plotter(args)
        sleep_fn = plotter.plt.pause
    else:
        plotter = None
        sleep_fn = time.sleep
    errs_max = 1 if not args.bt else 5
    errs_left = errs_max
    try:
        start = ts = time.time()
        while True:
            # Query data
            data = dev.query_raw(args.tout, sleep_fn)
            if not data:
                if fname and args.progress:
                    print('~', end='', flush=True)
                if plotter and plotter.is_closed():
                    return 0
                errs_left -= 1
                if errs_left <= 0:
                    log.error('\nno data')
                    return -1
                continue
            else:
                errs_left = errs_max
            t = ts - start
            val = Device.get_value(data)
            val_chan = Device.get_channel(data)
            val_good = not math.isnan(val)
            # Output data
            if val_good or args.keep_nan:
                if val_chan == 0:
                    if val_good: # apply value transformation
                        val = (val - args.offset) * args.mult
                    print(out_fmt % (ts if args.epoch else t, args.delimiter, val), file=out_file)
                elif alt_file:
                    print(out_fmt % (ts if args.epoch else t, args.delimiter, val), file=alt_file)
            if fname and args.progress:
                # Show progress
                print('.' if val_good else '!', end='', flush=True)
            if args.stat:
                # Update stat
                stat[val_chan].account(val)
            if plotter:
                if plotter.is_closed():
                    return 0
                # Update plot
                plotter.update(t, val, val_chan)
            # Introduce delay according to acquisition interval
            now = time.time()
            elapsed = now - ts
            if elapsed < args.interval:
                sleep_fn(args.interval - elapsed)
                ts += args.interval
            else:
                ts = now
    finally:
        dev.close()
        if fname:
            out_file.close()
            if args.progress:
                print()
        if alt_fname:
            alt_file.close()
        if args.stat:
            print('\n--- data statistics:')
            stat[0].print()
            if alt_fname:
                print('\n--- alternative channel:')
                stat[1].print()

def do_plot(args):
    """Just plots input files"""
    import matplotlib.pyplot as plt
    for fname in args.input_files:
        xdata, ydata = [], []
        with open(fname, 'r') as f:
            for line in f:
                xy = line.split()
                if len(xy) != 2:
                    continue
                try:
                    x, y = float(xy[0]), float(xy[1])
                except ValueError:
                    continue
                xdata.append(x)
                ydata.append(y)
        name = os.path.basename(fname)
        name = os.path.splitext(name)[0]
        plt.plot(xdata, ydata, label=name)
    if len(args.input_files) == 1:
        plt.title(args.input_files[0])
    else:
        plt.legend()
    plt.show()

def main():
    parser = argparse.ArgumentParser(
            description='UNI-T UT61E+ data acquisition tool',
            usage='%(prog)s [options] list|once|data [command options]'
        )

    def get_help(args):
        parser.print_help()
        return 1

    parser.set_defaults(func=get_help)

    parser.register('type', 'hex-int', lambda s: int(s, 16))
    parser.add_argument('--VID', type='hex-int', required=False, metavar='HEX', default=DEF_VID,
            help='device vendor id (optional)')
    parser.add_argument('--PID', type='hex-int', required=False, metavar='HEX', default=DEF_PID,
            help='device product id (optional)')
    parser.add_argument('--path', '--addr', type=str, required=False,
            help='device path or Bluetooth mac address (optional, auto detect by default)')
    parser.add_argument('--tout', type=float, required=False, default=DEF_TOUT, metavar='SECONDS',
            help='device read timeout (optional, default is %.0f sec)' % DEF_TOUT)
    parser.add_argument('-B', '--bt', action='store_true',
            help='use UT-D07B Bluetooth adapter for communicating with device')
    parser.add_argument('--name', type=str, required=False, default=DEF_BT_NAME,
            help='set Bluetooth adapter name (optional, default is UT-D07B)')

    subparsers = parser.add_subparsers()
    subparsers.add_parser('list',
            help='list path for connected devices'
        ).set_defaults(func=do_list)
    subparsers.add_parser('once',
            help='get single reading'
        ).set_defaults(func=do_once)
    data_parser = subparsers.add_parser('data',
            help='read data continuously',
            formatter_class=lambda prog: argparse.HelpFormatter(prog, max_help_position=40)
        )
    data_parser.set_defaults(func=do_data)

    data_parser.add_argument('-i', '--interval', type=float, required=False, default=1., metavar='SECONDS',
            help='data acquisition interval (default is 1 sec)')
    data_parser.add_argument('-f', '--file', type=str, required=False, metavar='FILENAME',
            help='output file (optional, stdout by default), may have folder part and/or date time pattern, like %%Y-%%m-%%d/%%H%%M%%S.data')
    data_parser.add_argument('-a', '--alt-file', type=str, required=False, metavar='FILENAME',
            help='alternative channel output file name (for storing AC voltage in DC mode)')
    data_parser.add_argument('--keep-nan', action='store_true',
            help='keep invalid data values (NaN) resulting from overload (optional, discarding them by default)')
    data_parser.add_argument('-p', '--progress', action='store_true',
            help='show progress when writing to file')
    data_parser.add_argument('-o', '--offset', type=float, required=False, metavar='VALUE', default=0,
            help='set data offset')
    data_parser.add_argument('-m', '--mult', type=float, required=False, metavar='VALUE', default=1,
            help='set data multiplier')
    data_parser.add_argument('-e', '--epoch', action='store_true',
            help='use epoch timestamps (optional, use time since start by default)')
    data_parser.add_argument('-d', '--delimiter', type=str, default='', metavar='SYMBOL',
            help='data delimiter on output (optional, space by default)')
    data_parser.add_argument('-s', '--stat', action='store_true',
            help='output statistic upon termination')
    data_parser.add_argument('-g', '--graph', action='store_true',
            help='show data graph')
    data_parser.add_argument('-w', '--wnd', type=int, required=False, metavar='SAMPLES',
            help='data graph window samples (optional, show all samples by default)')
    data_parser.add_argument('-z', '--with-zero', action='store_true',
            help='make sure zero is within data graph vertical axis range')
    data_parser.add_argument('-t', '--title', type=str, required=False, metavar='TEXT',
            help='set data graph window title')
    data_parser.add_argument('--plot-title', type=str, required=False, metavar='TEXT',
            help='set data plot title')
    data_parser.add_argument('--alt-title', type=str, required=False, metavar='TEXT',
            help='set alternative channel data plot title')
    data_parser.add_argument('--hline', type=float, metavar='VAL', action='append',
            help='draw horizontal line through the specified vertical axis value (may be used multiple times)')
    data_parser.add_argument('--alt-hline', type=float, metavar='VAL', action='append',
            help='draw horizontal line through the specified alternative channel vertical axis value (may be used multiple times)')
    data_parser.add_argument('--line-style', type=str, required=False, metavar='STR', default='-',
            help="line style specifier (optional, default is '-')")
    data_parser.add_argument('--hline-style', type=str, required=False, metavar='STR', default='--',
            help="horizontal line style specifier (optional, default is '--')")
    data_parser.add_argument('--line-color', type=str, required=False, metavar='STR', default='C0',
            help="line color specifier (optional, default is 'C0')")
    data_parser.add_argument('--alt-line-color', type=str, required=False, metavar='STR', default='C2',
            help="alternative channel line color specifier (optional, default is 'C2')")
    data_parser.add_argument('--hline-color', type=str, required=False, metavar='STR', default='C1',
            help="horizontal line color specifier (optional, default is 'C1')")
    data_parser.add_argument('--cfg-save', type=str, required=False, metavar='FILENAME',
            help='save command line options to the file with given name')
    data_parser.add_argument('-c', '--cfg-load', type=str, required=False, metavar='FILENAME',
            help='load command line options from the file with given name')

    plot_parser = subparsers.add_parser('plot', help='plot data file(s)')
    plot_parser.set_defaults(func=do_plot)
    plot_parser.add_argument('input_files', nargs='+', help='list of input files')

    args = parser.parse_args()

    cfg_load_fname = getattr(args, 'cfg_load', None)
    if cfg_load_fname:
        with open(cfg_load_fname, 'r') as f:
            opts = json.loads(f.read())
        data_parser.set_defaults(func = args.func, **opts)
        args = parser.parse_args()

    try:
        return args.func(args)
    except KeyboardInterrupt:
        return 0

if __name__ == '__main__':
    sys.exit(main())
